#@ load("@ytt:data","data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind": "Namespace", "metadata":{"name": data.values.staging_namespace}}), expects=1
---
metadata:
  #@overlay/match missing_ok=True
  labels:
    #@overlay/match missing_ok=True
    cf-for-k8s.cloudfoundry.org/cf-workloads-staging-ns: ""
