---
resources:
- name: cf-for-k8s-master
  type: git
  icon: github-box
  source:
    branch: master
    uri: git@github.com:cloudfoundry/cf-for-k8s
    private_key: ((cf_for_k8s_readonly_deploy_key.private_key))
    ignore_paths:
      - ci/**
- name: every-10-minutes
  type: time
  icon: clock-outline
  source:
    interval: 10m

# Extract common platform and image_resource details so task configs can be more concise
x-config: &common-task-config
  platform: linux
  image_resource:
    type: docker-image
    source:
      repository: relintdockerhubpushbot/cf-for-k8s-ci

# Extract common platform and image_resource details so task configs can be more concise
test-runner-config: &common-test-config
  platform: linux
  image_resource:
    type: docker-image
    source:
      repository: relintdockerhubpushbot/cf-test-runner

jobs:
- name: deploy-cf
  public: true
  plan:
  - get: cf-for-k8s-master
    trigger: true
  - get: every-10-minutes
    trigger: true
  - task: delete-cf
    config:
      <<: *common-task-config
      run:
        path: /bin/bash
        args:
        - -ec
        - |
          export KUBECONFIG=kube-config.yml
          gcloud auth activate-service-account --key-file=<(echo '((ci_k8s_gcp_service_account_json))') --project='((ci_k8s_gcp_project_name))' 1>/dev/null 2>&1
          gcloud container clusters get-credentials '((ci_k8s_gke_cluster_name))' --zone '((ci_k8s_gcp_project_zone))' 1>/dev/null 2>&1

          kapp delete -a cf --yes

  - task: generate-cf-install-values
    config:
      <<: *common-task-config
      outputs:
      - name: cf-install-values
      run:
        path: /bin/bash
        args:
        - -ec
        - |
          cat > cf-install-values/cf-install-values.yml <<EOF
          #@data/values
          ---
          system_domain: ((ci_k8s_domain))
          app_domains:
          #@overlay/append
          - ((ci_k8s_domain))
          cf_admin_password: ((ci_k8s_cf_admin_password))

          cf_db:
            admin_password: ((ci_k8s_cf_db_admin_password))

          capi:
            database:
              password: ((ci_k8s_capi_db_password))

          system_certificate:
            crt: &crt ((ci_k8s_system_certificate_cert))
            key: &key ((ci_k8s_system_certificate_key))
            ca: ((ci_k8s_system_certificate_ca_cert))

          uaa:
            database:
              password: ((ci_k8s_uaa_db_password))
            admin_client_secret: ((ci_k8s_uaa_admin_client_secret))
            certificate:
              crt: *crt
              key: *key

          doppler:
            tls:
              crt: *crt
              key: *key

          eirini:
            tls:
              crt: *crt
              key: *key
          EOF

  - task: install-cf
    config:
      <<: *common-task-config
      inputs:
      - name: cf-for-k8s-master
      - name: cf-install-values
      run:
        path: /bin/bash
        args:
        - -ec
        - |
          export KUBECONFIG=kube-config.yml
          gcloud auth activate-service-account --key-file=<(echo '((ci_k8s_gcp_service_account_json))') --project='((ci_k8s_gcp_project_name))' 1>/dev/null 2>&1
          gcloud container clusters get-credentials '((ci_k8s_gke_cluster_name))' --zone '((ci_k8s_gcp_project_zone))' 1>/dev/null 2>&1
          cf-for-k8s-master/bin/install-cf.sh cf-install-values/cf-install-values.yml

  - task: configure-dns
    config:
      <<: *common-task-config
      params:
        DNS_DOMAIN: ((ci_k8s_domain))
        DNS_ZONE_NAME: ((ci_k8s_dns_zone_name))
      run:
        path: /bin/bash
        args:
        - -ec
        - |
          export KUBECONFIG=kube-config.yml
          gcloud auth activate-service-account --key-file=<(echo '((ci_k8s_gcp_service_account_json))') --project='((ci_k8s_gcp_project_name))' 1>/dev/null 2>&1
          gcloud container clusters get-credentials '((ci_k8s_gke_cluster_name))' --zone '((ci_k8s_gcp_project_zone))' 1>/dev/null 2>&1

          echo "Discovering Istio Gateway LB IP"
          external_static_ip=$(kubectl get services/istio-ingressgateway -n istio-system --output="jsonpath={.status.loadBalancer.ingress[0].ip}")

          echo "Configuring DNS for external IP: ${external_static_ip}"
          gcloud dns record-sets transaction start --zone="${DNS_ZONE_NAME}"
          gcp_records_json="$( gcloud dns record-sets list --zone="${DNS_ZONE_NAME}" --name "*.${DNS_DOMAIN}" --format=json )"
          record_count="$( echo "${gcp_records_json}" | jq 'length' )"
          if [ "${record_count}" != "0" ]; then
            existing_record_ip="$( echo "${gcp_records_json}" | jq -r '.[0].rrdatas | join(" ")' )"
            gcloud dns record-sets transaction remove --name "*.${DNS_DOMAIN}" --type=A --zone="${DNS_ZONE_NAME}" --ttl=5 "${existing_record_ip}" --verbosity=debug
          fi
          gcloud dns record-sets transaction add --name "*.${DNS_DOMAIN}" --type=A --zone="${DNS_ZONE_NAME}" --ttl=5 "${external_static_ip}" --verbosity=debug

          gcloud dns record-sets transaction execute --zone="${DNS_ZONE_NAME}" --verbosity=debug

          # Wait for DNS to propagate
          resolved_ip=''
          while [ "$resolved_ip" != "$external_static_ip" ]; do
            sleep 5
            resolved_ip=$(nslookup "*.$DNS_DOMAIN" | grep Address | grep -v ':53' | cut -d ' ' -f2)
            echo "resolved IP = $resolved_ip"
            echo "external static IP = $external_static_ip"
          done

  - task: run-smoke-test
    config:
      <<: *common-test-config
      inputs:
      - name: cf-for-k8s-master
      params:
        SMOKE_TEST_API_ENDPOINT: https://api.((ci_k8s_domain))
        SMOKE_TEST_APPS_DOMAIN: ((ci_k8s_domain))
        SMOKE_TEST_USERNAME: admin
        SMOKE_TEST_PASSWORD: ((ci_k8s_cf_admin_password))
      run:
        path: /bin/sh
        args:
        - -ec
        - |
          cd cf-for-k8s-master/tests/smoke
          ginkgo .

  - task: delete-cf
    config:
      <<: *common-task-config
      run:
        path: /bin/bash
        args:
        - -ec
        - |
          export KUBECONFIG=kube-config.yml
          gcloud auth activate-service-account --key-file=<(echo '((ci_k8s_gcp_service_account_json))') --project='((ci_k8s_gcp_project_name))' 1>/dev/null 2>&1
          gcloud container clusters get-credentials '((ci_k8s_gke_cluster_name))' --zone '((ci_k8s_gcp_project_zone))' 1>/dev/null 2>&1

          kapp delete -a cf --yes
