---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-for-k8s-ci

inputs:
- name: cf-for-k8s-repo

params:
  VENDIR_GITHUB_API_TOKEN:
  REPO_DIR: cf-for-k8s-pr-all-branches-and-forks

run:
  path: cf-for-k8s-pr-all-branches-and-forks/ci/tasks/check-vendir-sync.sh
