apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-app-ingress
  namespace: cf-workloads
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: cf-system
      podSelector:
        matchLabels:
          app.kubernetes.io/component: router
    - namespaceSelector:
        matchLabels:
          name: cf-system
      podSelector:
        matchLabels:
          app.kubernetes.io/component: adapter
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: cf-workloads-app-psp
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: docker/default,runtime/default
    seccomp.security.alpha.kubernetes.io/defaultProfileName: runtime/default
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
  - ALL
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535
  fsGroup:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535
  readOnlyRootFilesystem: false
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: eirini
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: runtime/default
    seccomp.security.alpha.kubernetes.io/defaultProfileName: runtime/default
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
  - ALL
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535
  fsGroup:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535
  readOnlyRootFilesystem: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eirini
  namespace: cf-system
data:
  opi.yml: |
    opi:
      app_namespace: cf-workloads
      cc_certs_secret_name: "secrets-2.16.4-2"
      registry_address: "registry.not-used:443"
      registry_secret_name: registry-credentials
      eirini_address: "https://eirini-opi.cf-system.svc.cluster.local:8085"
      downloader_image: eirini/recipe-downloader@sha256:4c42d4f3dd749144b3468ecd48a14d3849ab5ec08b344b729e73e473ea6b0051
      executor_image: eirini/recipe-executor@sha256:730c7dbf9625ed57da358791370d1ea6f526f0ccbcd82bdfb0bf184c02ca1f06
      uploader_image: eirini/recipe-uploader@sha256:2a28bc10fc0d7811818a3a922baa4e4739d2b33f0bba21bfc81d4826f69aed6f
      cc_cert_path: "/workspace/jobs/opi/secrets/cc.crt"
      cc_key_path: "/workspace/jobs/opi/secrets/cc.key"
      cc_ca_path: "/workspace/jobs/opi/secrets/cc.ca"
      rootfs_version: v75.0.0
      client_ca_path: "/workspace/jobs/opi/secrets/eirini.ca"
      server_cert_path: "/workspace/jobs/opi/secrets/eirini-server.crt"
      server_key_path: "/workspace/jobs/opi/secrets/eirini-server.key"
      tls_port: 8085
      disk_limit_mb: 2048
  routing.yml: |
    app_namespace: cf-workloads
    nats_ip: "nats-nats.cf-system.svc.cluster.local"
    nats_port: 4222
  metrics.yml: |
    app_namespace: cf-workloads
    loggregator_address: "doppler-doppler-set.cf-system.svc.cluster.local:8082"
    loggergator_cert_path: "/etc/eirini/secrets/doppler.crt"
    loggregator_key_path: "/etc/eirini/secrets/doppler.key"
    loggregator_ca_path: "/etc/eirini/secrets/doppler.ca"
  events.yml: |
    app_namespace: cf-workloads
    cc_internal_api: "https://api.cf-system.svc.cluster.local:9023"
    cc_cert_path: "/etc/eirini/secrets/cc.crt"
    cc_key_path: "/etc/eirini/secrets/cc.key"
    cc_ca_path: "/etc/eirini/secrets/cc.ca"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opi
  namespace: cf-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cf-workloads-app-role
  namespace: cf-workloads
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - cf-workloads-app-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eirini-role
  namespace: cf-workloads
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - update
  - delete
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eirini-role
  namespace: cf-system
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - eirini
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cf-workloads-app-rolebinding
  namespace: cf-workloads
roleRef:
  kind: Role
  name: cf-workloads-app-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  namespace: cf-workloads
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eirini-rolebinding
  namespace: cf-system
roleRef:
  kind: Role
  name: eirini-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: opi
  namespace: cf-system
- kind: ServiceAccount
  name: eirini-rootfs-patcher
  namespace: cf-system
- kind: ServiceAccount
  name: eirini-secret-smuggler
  namespace: cf-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eirini-rolebinding
  namespace: cf-workloads
roleRef:
  kind: Role
  name: eirini-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: opi
  namespace: cf-system
---
apiVersion: v1
kind: Service
metadata:
  name: eirini
  namespace: cf-system
spec:
  ports:
  - port: 8085
    protocol: TCP
    name: https
  selector:
    name: eirini
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eirini
  namespace: cf-system
spec:
  selector:
    matchLabels:
      name: eirini
  template:
    metadata:
      labels:
        name: eirini
        eirinifs_version: v75.0.0
    spec:
      dnsPolicy: ClusterFirst
      serviceAccountName: opi
      volumes:
      - name: config-map-volume
        configMap:
          name: eirini
          items:
          - key: opi.yml
            path: opi.yml
      - name: cf-secrets
        projected:
          sources:
          - secret:
              name: eirini-internal-tls-certs
              items:
              - key: tls.crt
                path: cc.crt
              - key: tls.key
                path: cc.key
          - secret:
              name: eirini-internal-tls-certs
              items:
              - key: tls.ca
                path: cc.ca
          - secret:
              name: eirini-internal-tls-certs
              items:
              - key: tls.crt
                path: eirini-server.crt
              - key: tls.key
                path: eirini-server.key
          - secret:
              name: system-domain-cert
              items:
              - key: tls.ca
                path: eirini.ca
      securityContext:
        runAsNonRoot: true
      containers:
      - name: opi
        image: eirini/opi@sha256:aec40996b2408df32657553d56e97e97097852705ec3a7c9c6cef5c80898b622
        imagePullPolicy: Always
        volumeMounts:
        - name: config-map-volume
          mountPath: /workspace/jobs/opi/config
        - name: cf-secrets
          mountPath: /workspace/jobs/opi/secrets
        ports:
        - containerPort: 8085
          name: https
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
