#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")
#@ load("@ytt:library", "library")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")
#@ load("must_exist.star", "must_exist")

#@ def add_cf_blobstore_namespace():
#@overlay/match by=overlay.all, expects="1+"
---
metadata:
  #@overlay/match missing_ok=True
  namespace: cf-blobstore
#@ end

---
apiVersion: v1
kind: Namespace
metadata:
  name: cf-blobstore

#@overlay/match by=overlay.subset({"kind": "Secret", "metadata": {"name": "cf-blobstore-minio"}})
---
data:
  accesskey: #@ base64.encode(must_exist(data.values, "cf_blobstore.access_key"))
  secretkey: #@ base64.encode(must_exist(data.values, "cf_blobstore.secret_key"))

--- #@ template.replace(overlay.apply(library.get("minio").eval(), add_cf_blobstore_namespace()))

#! #@overlay/match by=overlay.subset({"kind": "Deployment", "metadata": {"name": "cf-blobstore-minio"}})
#! ---
#! spec:
#!   #@overlay/match
#!   template:
#!     #@overlay/match
#!     spec:
#!       #@overlay/match
#!       containers:
#!         #@overlay/match by=overlay.subset({"name": "minio"})
#!       - name: minio
#!         #@overlay/match
#!         image: "index.docker.io/minio/minio@sha256:8786346b1e200647c34f4a614f3186c9374d24fbfe309c5d6ffe3efb06e68392"
