#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.or_op(overlay.subset({"kind":"ConfigMap"}), overlay.subset({"kind":"Secret"})), expects="1+"
#@overlay/match-child-defaults missing_ok=True
---
metadata:
  annotations:
    kapp.k14s.io/versioned: ""
