---
apiVersion: v1
kind: Secret
metadata:
  name: system-domain-cert
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  tls.crt: {{ .Values.system_certificate.crt }}
  tls.key: {{ .Values.system_certificate.key }}
  tls.ca: {{ .Values.system_certificate.ca }}

