---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: uaa-external-virtual-service
  namespace: {{ .Values.system_namespace }}
spec:
  hosts:
  - uaa.{{ .Values.system_domain }}
  - login.{{ .Values.system_domain }}
  gateways:
  - {{ .Values.system_namespace }}/istio-ingressgateway
  http:
  - route:
    - destination:
        host: uaa.{{ .Values.system_namespace }}.svc.cluster.local
        port:
          number: 8080
