---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-for-k8s-ci

inputs:
  - name: cf-for-k8s-ci

params:
  GCP_SERVICE_ACCOUNT_JSON:
  GCP_PROJECT_NAME:
  GCR_REPO_NAME:

run:
  path: cf-for-k8s-ci/ci/tasks/clean-gcr/task.sh
